require './test_common'

require 'test/tc_assignment'
require 'test/tc_besteffort_delivery'
require 'test/tc_bfs'
require 'test/tc_carts'
require 'test/tc_causal_delivery'
puts "tc_chord disabled temporarily"    #require 'test/tc_chord'
require 'test/tc_dastardly_delivery'
require 'test/tc_demonic_delivery'
puts "tc_e2e_bfs disabled temporarily" #require 'test/tc_e2e_bfs'
require 'test/tc_heartbeat'
require 'test/tc_kvs'
require 'test/tc_lamport'
puts "tc_leader disabled temporarily" #require 'test/tc_leader'
require 'test/tc_member'
require 'test/tc_monotone_cart'
puts "tc_mi disabled temporarily" #require 'test/tc_mi'
puts "tc_mvcc disabled temporarily" #require 'test/tc_mvcc'
require 'test/tc_multicast'
require 'test/tc_mv_kvs'
require 'test/tc_ordering'
require 'test/tc_reliable_delivery'
require 'test/tc_timers'
require 'test/tc_vector_clock'
require 'test/tc_voting'
