require 'test/cart_workloads.rb'
require 'test/kvs_workloads.rb'
require 'test/tc_2pc.rb'
require 'test/tc_assignment.rb'
require 'test/tc_besteffort_delivery.rb'
require 'test/tc_bfs.rb'
require 'test/tc_carts.rb'
puts "tc_chord.rb disabled temporarily"    #require 'test/tc_chord.rb'
require 'test/tc_dastardly_delivery.rb'
require 'test/tc_demonic_delivery.rb'
puts "tc_e2e_bfs.rb disabled temporarily" #require 'test/tc_e2e_bfs.rb'
require 'test/tc_heartbeat.rb'
require 'test/tc_kvs.rb'
require 'test/tc_lamport.rb'
puts "tc_leader.rb disabled temporarily" #require 'test/tc_leader.rb'
require 'test/tc_member.rb'
puts "tc_mi.rb disabled temporarily" #require 'test/tc_mi.rb'
puts "tc_mvcc disabled temporarily" #require 'test/tc_mvcc.rb'
require 'test/tc_multicast.rb'
require 'test/tc_mv_kvs.rb'
require 'test/tc_ordering.rb'
require 'test/tc_reliable_delivery.rb'
require 'test/tc_timers.rb'
require 'test/tc_vector_clock.rb'
require 'test/tc_voting.rb'
