require './test_common'

require 'test/tc_assignment'
require 'test/tc_besteffort_delivery'
require 'test/tc_bfs'
#require 'test/tc_carts'
#require 'test/tc_chord'
require 'test/tc_dastardly_delivery'
require 'test/tc_demonic_delivery'
#require 'test/tc_e2e_bfs'
require 'test/tc_heartbeat'
require 'test/tc_kvs'
require 'test/tc_lamport'
#require 'test/tc_leader'
require 'test/tc_member'
require 'test/tc_multicast'
require 'test/tc_ordering'
require 'test/tc_reliable_delivery'
require 'test/tc_timers'
require 'test/tc_voting'

# require 'test/cart_workloads.rb'
# require 'test/kvs_workloads.rb'
# #require 'test/tc_2pc.rb'
# require 'test/tc_assignment.rb'
# require 'test/tc_besteffort_delivery.rb'
# require 'test/tc_bfs.rb'
# require 'test/tc_carts.rb'
# #require 'test/tc_chord.rb'
# require 'test/tc_dastardly_delivery.rb'
# require 'test/tc_demonic_delivery.rb'
# #require 'test/tc_e2e_bfs.rb'
# require 'test/tc_heartbeat.rb'
# require 'test/tc_kvs.rb'
# require 'test/tc_lamport.rb'
# #require 'test/tc_leader.rb'
# require 'test/tc_member.rb'
# #require 'test/tc_mi.rb'
# require 'test/tc_mvcc.rb'
# require 'test/tc_multicast.rb'
# require 'test/tc_mv_kvs.rb'
# require 'test/tc_ordering.rb'
# require 'test/tc_reliable_delivery.rb'
# require 'test/tc_timers.rb'
# require 'test/tc_vector_clock.rb'
# require 'test/tc_voting.rb'
